### ISSUE TITLE
Bugs with level completion

### ISSUE THREAD

**Issue by Archichil** [Riborok/2DTanks#1]
There are some problems when you collect all the keys on the map. According to the game logic, after the moment when you collect all keys on the map, the game should automatically refresh the map to another level, but it didn't happen. To force rerender you should switch to other tab in your browser, then come back to tank's tab. Also there is another problem. How many levels you've gone through, that's how many timers will go on. What does it mean... When you complete one level and step into another, the timer of previous level doesn't stop, and it's going with the timer of current level, switching every second between timer's values. (3 levels completed = 3 timers are showing their values switching every second)

**Comment by Riborok** [comment]
Thanks for the report. The last commit broke everything
