### ISSUE TITLE
Game over (design issue)

### ISSUE THREAD

**Issue by Archichil** [Riborok/2DTanks#2]
For example, when defender wins, game is still playable, you can collect the boxes with bullets, kill each other, but you can not collect the keys, they become uncollectable. I think it's design flaw.

**Comment by Archichil** [comment]
But when attacker wins, game stops (you can move your tanks), but whatever, boxes with bullets continue to appear

**Comment by Riborok** [comment]
Thanks for the report. The last commit broke everything
